FROM node:18.17.0-slim
WORKDIR /app

# Setup system
RUN apt-get update
RUN apt-get install openssl -y
RUN npm install -g pnpm
ENV CI=true

# Install dependencies
COPY ./ /app
RUN pnpm install --frozen-lockfile
RUN cd admin && pnpm prisma generate

CMD [ "tail", "-F", "/dev/null" ]
