FROM node:18.15.0-slim
WORKDIR /app

# Setup system
RUN apt-get update
RUN apt-get install openssl -y
RUN apt-get install unzip -y
RUN apt-get install curl -y
RUN npm install -g pnpm
ENV CI=true

# Install dependencies
COPY ./ /app
RUN pnpm install --frozen-lockfile
RUN scripts/deno_install.sh

RUN cd admin && pnpm playwright install-deps
RUN cd api && pnpm prisma generate
RUN pnpm build

CMD [ "tail", "-F", "/dev/null" ]
