import {
	IconBlockquote,
	IconH1,
	IconH2,
	IconH3,
	IconPilcrow,
	IconChevronDown,
	IconPlus,
	IconCode,
	IconBold,
	IconItalic,
	IconUnderline,
	IconStrikethrough,
	IconSelector,
	IconCheck,
	IconAlignLeft,
	IconAlignCenter,
	IconAlignRight,
	IconAlignJustified,
	IconLineHeight,
	IconList,
	IconListNumbers,
} from "@tabler/icons-react";

export const icons = {
	Paragraph: IconPilcrow,
	H1: IconH1,
	H2: IconH2,
	H3: IconH3,
	BlockQuote: IconBlockquote,
	Code: IconCode,

	Bold: IconBold,
	Italic: IconItalic,
	Underline: IconUnderline,
	Strikethrough: IconStrikethrough,

	ArrowDown: IconChevronDown,
	ArrowUpDown: IconSelector,
	Plus: IconPlus,
	Check: IconCheck,

	AlignLeft: IconAlignLeft,
	AlignCenter: IconAlignCenter,
	AlignRight: IconAlignRight,
	AlignJustify: IconAlignJustified,
	LineHeight: IconLineHeight,
	Ul: IconList,
	Ol: IconListNumbers,
};
