import {
	IconBlockquote,
	IconH1,
	IconH2,
	IconH3,
	IconPilcrow,
	IconChevronDown,
	IconPlus,
	IconCode,
	IconBold,
	IconItalic,
	IconUnderline,
	IconStrikethrough,
	IconSelector,
	IconCheck,
	IconAlignLeft,
	IconAlignCenter,
	IconAlignRight,
	IconAlignJustified,
	IconLineHeight,
	IconList,
	IconListNumbers,
	IconLink,
	IconCursorText,
	IconExternalLink,
	IconLinkOff,
	IconSuperscript,
	IconSubscript,
	IconTrash,
	IconPhoto,
	IconMovie,
	IconBorderBottom,
	IconBorderTop,
	IconBorderLeft,
	IconBorderRight,
	IconBorderNone,
	IconBorderAll,
	IconLayersIntersect2,
	IconLayersDifference,
	IconTable,
	IconTableColumn,
	IconMinus,
	IconTableRow,
	IconH4,
	IconH5,
	IconH6,
	IconSeparator,
	IconGripVertical,
} from "@tabler/icons-react";

export const icons = {
	Paragraph: IconPilcrow,
	H1: IconH1,
	H2: IconH2,
	H3: IconH3,
	H4: IconH4,
	H5: IconH5,
	H6: IconH6,
	BlockQuote: IconBlockquote,
	Code: IconCode,
	Hr: IconSeparator,

	Bold: IconBold,
	Italic: IconItalic,
	Underline: IconUnderline,
	Strikethrough: IconStrikethrough,

	ArrowDown: IconChevronDown,
	ArrowUpDown: IconSelector,
	Plus: IconPlus,
	Minus: IconMinus,
	Check: IconCheck,
	DragHandle: IconGripVertical,

	AlignLeft: IconAlignLeft,
	AlignCenter: IconAlignCenter,
	AlignRight: IconAlignRight,
	AlignJustify: IconAlignJustified,
	LineHeight: IconLineHeight,
	Ul: IconList,
	Ol: IconListNumbers,

	Link: IconLink,
	ExternalLink: IconExternalLink,
	Unlink: IconLinkOff,
	Text: IconCursorText,
	Superscript: IconSuperscript,
	Subscript: IconSubscript,

	Image: IconPhoto,
	Embed: IconMovie,
	Delete: IconTrash,

	Table: IconTable,
	Column: IconTableColumn,
	Row: IconTableRow,
	BorderBottom: IconBorderBottom,
	BorderTop: IconBorderTop,
	BorderLeft: IconBorderLeft,
	BorderRight: IconBorderRight,
	BorderNone: IconBorderNone,
	BorderAll: IconBorderAll,
	Combine: IconLayersIntersect2,
	Ungroup: IconLayersDifference,
};
