export default function Head() {
	return (
		<>
			<title>Create T3 App</title>
			<meta name="description" content="Generated by create-t3-app" />
			<link rel="icon" href="/favicon.ico" />
			<link rel="icon" href="/favicon.ico" />
		</>
	);
}
