import React from "react";

export default function Head(props: { children: React.ReactNode }) {
	return (
		<html>
			<head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/admin/favicon.ico" />
			</head>
			<body>{props.children}</body>
		</html>
	);
}
